version: '3.8'

services:
  oxcs:
    build: ./
    command: ./app
    ports:
      - 8182:8182
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_PASSWORD: qwerty
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: nik
      DB_NAME: nik
      DB_SSLMODE: disable
      container-name: oxcs
  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "nik"
      POSTGRES_USER: "nik"
      POSTGRES_PASSWORD: "qwerty"
    container_name: oxcs-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U nik" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5436:5432