version: '3.8'

services:
  app:
    image: m1m1kq/oxcs
    ports:
      - 8182:6000
    volumes:
      - "~/apps-data/files-data/${COMPANY}/:/app/assets/uploads/"
    depends_on:
      db:
        condition: service_healthy
      app-converter:
        condition: service_started
    environment:
      PORT: 6000
      APP_ADDRESS: http://172.20.10.7:8184
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: "${DB}"
      DB_NAME: "${DB}"
      DB_SSLMODE: disable
  app-converter:
    restart: always
    image: m1m1kq/oxcs-converter
    ports:
      - 5001:5000
    environment:
      APP_ADDR: http://app:6000
  db:
    restart: always
    image: postgres:latest
    volumes:
      - "~/apps-data/tables-data/${COMPANY}:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: "${DB}"
      POSTGRES_USER: "${DB}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5436:5432